namespace Cake.CycloneDX.Tools.CdxDotNet;

/// <summary>
/// A set of packages to exclude from a BOM generated by the CycloneDX .NET tool.
/// </summary>
public class ExcludeFilterHashSet : HashSet<ExcludeFilter>
{
    /// <summary>
    /// Returns the filters as the comma-separated list the tool's <c>--exclude-filter</c> option expects.
    /// </summary>
    /// <returns>The filters, such as <c>name1@1.0.0,name2</c>.</returns>
    public string ToArgumentString()
    {
        return string.Join(',', this);
    }

    /// <summary>
    /// Adds a filter that excludes one version of a package.
    /// </summary>
    /// <param name="name">The package name.</param>
    /// <param name="version">The package version.</param>
    public void Add(string name, string version)
    {
        Add(new ExcludeFilter(name, version));
    }

    /// <summary>
    /// Adds a filter that excludes all versions of a package.
    /// </summary>
    /// <param name="name">The package name.</param>
    public void Add(string name)
    {
        Add(new ExcludeFilter(name));
    }
}