namespace Cake.CycloneDX.Tools.CdxDotNet;

/// <summary>
/// A package to exclude from a BOM generated by the CycloneDX .NET tool.
/// </summary>
/// <param name="Name">The package name.</param>
/// <param name="Version">The package version, or <see langword="null"/> to exclude all versions of the package.</param>
public record struct ExcludeFilter(string Name, string? Version = null)
{
    /// <summary>
    /// Returns the filter in the form the CycloneDX .NET tool expects: <c>name@version</c>, or <c>name</c> when no version is set.
    /// </summary>
    /// <returns>The filter as a string.</returns>
    public override string ToString()
    {
        return Version is null ? Name : $"{Name}@{Version}";
    }
}