<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="All" />
    <PackageVersion Include="Cake.Frosting" Version="6.3.0" />
    <PackageVersion Include="CycloneDX.Core" Version="8.0.3" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="Cake.Core" Version="6.0.0" />
    <PackageVersion Include="Cake.Testing" Version="6.0.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.assert" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup Label="Transitive Dependencies">
    <PackageVersion Include="System.Text.Json" Version="*" />
  </ItemGroup>
</Project>