name: Build

on:
  push:
    branches-ignore:
      - "dependabot/**" # Will still build PRs, but not the branches themself
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Fetch all branches and tags
        run: git fetch --unshallow --prune
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 9.0.x        
      - name: Install CycloneDX tool
        run: dotnet tool install -g CycloneDX --version 5.2.0    
      - name: Build Cake.CycloneDX
        uses: cake-build/cake-action@v3
        with:
          project-path: build/Build.csproj
          target: All
          verbosity: Diagnostic
          